####系统默认配置多数据源格式， 系统默认采用HikariCP高性能数据库连接池
spring:
  datasource:
    default:
      hikari:
        url: jdbc:mysql://192.168.249.235:3306/iEMP?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: Mym7Root!
        driver-class-name: com.mysql.cj.jdbc.Driver
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 5
        pool-name: master
        max-lifetime: 1800000
    secondary: ds1,ds2
    ds1:
        hikari:
                  url: jdbc:mysql://192.168.249.235:3306/iEMP?useUnicode=true&characterEncoding=UTF-8&useSSL=false
                  username: root
                  password: Mym7Root!
                  driver-class-name: com.mysql.cj.jdbc.Driver
                  connection-test-query: SELECT 1 FROM DUAL
                  minimum-idle: 1
                  maximum-pool-size: 5
                  pool-name: master
                  max-lifetime: 1800000
    ds2:
        hikari:
                  url: jdbc:mysql://192.168.249.235:3306/iEMP?useUnicode=true&characterEncoding=UTF-8&useSSL=false
                  username: root
                  password: Mym7Root!
                  driver-class-name: com.mysql.cj.jdbc.Driver
                  connection-test-query: SELECT 1 FROM DUAL
                  minimum-idle: 1
                  maximum-pool-size: 5
                  pool-name: master
                  max-lifetime: 1800000
